### ISSUE TITLE
Bot currently not able to do anything

### ISSUE THREAD

**Issue by TeaJayed** [okkdev/cardian#3]
The bot just searches for a couple of minutes, stops and gives an error message.
Set up the bot again on the server but didnt work.

**Comment by okkdev** [comment]
Unfortunately there's nothing I can do at the moment, as that is an issue on Discord's side.
Today Discord added an additional digit to their snowflake IDs, but in the process broke a couple API endpoints. Seems like Cardian is affected because it's using interaction defer.
Let's hope Discord fixes it soon.

**Comment by TeaJayed** [comment]
Alright, thanks for the info!

**Comment by okkdev** [comment]
I'll leave it open and close it once the issue is resolved on Discord's part. :)

**Comment by okkdev** [comment]
Seems to be working again :)
